(function () {
  "use strict";
  var root=document.getElementById("monte-carlo-widget");if(!root||!window.FXW)return;
  var F=window.FXW,T=F.pick({
    ru:{balance:"Начальный капитал, USD",rate:"USD -> UZS",simulations:"Симуляций",trades:"Сделок в серии",wr:"Win rate, %",rr:"Reward/Risk",risk:"Риск на сделку, %",seed:"Seed",run:"Запустить симуляцию",median:"Медианный финал",bad:"Финал в худших 5%",dd:"Медианная макс. просадка",dd95:"Просадка в худших 5%",loss:"Вероятность закончить в минусе",dd20:"Вероятность просадки 20%+",ruin:"Риск потерять 50% капитала",streak:"Убыточная серия в худших 5%",note:"Это модель независимых сделок с постоянными WR, R:R и риском. Она не предсказывает рынок."},
    en:{balance:"Starting capital, USD",rate:"USD -> UZS",simulations:"Simulations",trades:"Trades per run",wr:"Win rate, %",rr:"Reward/Risk",risk:"Risk per trade, %",seed:"Seed",run:"Run simulation",median:"Median final balance",bad:"Final balance in worst 5%",dd:"Median max drawdown",dd95:"Drawdown in worst 5%",loss:"Probability of finishing down",dd20:"Probability of 20%+ drawdown",ruin:"Risk of losing 50% of capital",streak:"Losing streak in worst 5%",note:"This model assumes independent trades and constant WR, R:R and risk. It does not predict the market."},
    uz:{balance:"Boshlang'ich kapital, USD",rate:"USD -> UZS",simulations:"Simulyatsiyalar",trades:"Seriyadagi savdolar",wr:"Win rate, %",rr:"Reward/Risk",risk:"Har savdoda risk, %",seed:"Seed",run:"Simulyatsiyani boshlash",median:"Median yakuniy balans",bad:"Eng yomon 5% dagi balans",dd:"Median maksimal pasayish",dd95:"Eng yomon 5% dagi pasayish",loss:"Minusda tugash ehtimoli",dd20:"20%+ pasayish ehtimoli",ruin:"Kapitalning 50% ini yo'qotish riski",streak:"Eng yomon 5% dagi zarar seriyasi",note:"Model mustaqil savdolar va doimiy WR, R:R hamda riskni faraz qiladi. U bozorni bashorat qilmaydi."}
  });
  function field(label,id,value,extra){return '<label><span>'+label+'</span><input id="'+id+'" type="number" value="'+value+'" '+(extra||'')+'></label>';}
  root.innerHTML='<div class="fx-tool-grid">'+field(T.balance,'mco-balance',1000,'min="1"')+field(T.rate,'mco-rate',12500,'min="1"')+field(T.simulations,'mco-sims',1000,'min="100" max="10000" step="100"')+field(T.trades,'mco-trades',100,'min="10" max="1000"')+field(T.wr,'mco-wr',45,'min="0" max="100" step="0.1"')+field(T.rr,'mco-rr',2,'min="0.1" step="0.1"')+field(T.risk,'mco-risk',1,'min="0.1" max="20" step="0.1"')+field(T.seed,'mco-seed',42,'min="1" step="1"')+'</div><div class="fx-tool-actions"><button id="mco-run" type="button">'+T.run+'</button></div><div id="mco-result" class="fx-result" hidden></div><canvas id="mco-chart" class="fx-chart" width="900" height="300" hidden></canvas><p class="fx-tool-note">'+T.note+'</p>';
  function rng(seed){var state=Math.floor(seed)%2147483647;if(state<=0)state=1;return function(){state=state*48271%2147483647;return(state-1)/2147483646;};}
  function percentile(values,p){var a=values.slice().sort(function(x,y){return x-y;}),i=(a.length-1)*p/100,l=Math.floor(i),f=i-l;return l+1<a.length?a[l]+(a[l+1]-a[l])*f:a[l];}
  function val(id){return Number(document.getElementById(id).value);}
  function pct(value){return(value*100).toFixed(1)+'%';}
  function draw(finals,balance){var canvas=document.getElementById('mco-chart'),ctx=canvas.getContext('2d'),w=canvas.width,h=canvas.height;ctx.clearRect(0,0,w,h);ctx.fillStyle=getComputedStyle(document.documentElement).getPropertyValue('--md-default-bg-color')||'#fff';ctx.fillRect(0,0,w,h);var sorted=finals.slice().sort(function(a,b){return a-b;}),max=Math.max.apply(null,sorted),min=Math.min.apply(null,sorted);ctx.strokeStyle='#3b82f6';ctx.lineWidth=3;ctx.beginPath();sorted.forEach(function(v,i){var x=20+i/(sorted.length-1)*(w-40),y=h-20-(v-min)/(max-min||1)*(h-40);if(i===0)ctx.moveTo(x,y);else ctx.lineTo(x,y);});ctx.stroke();ctx.strokeStyle='#ef4444';var breakY=h-20-(1-min)/(max-min||1)*(h-40);ctx.beginPath();ctx.moveTo(20,breakY);ctx.lineTo(w-20,breakY);ctx.stroke();canvas.hidden=false;canvas.setAttribute('aria-label','Monte Carlo final balance distribution, starting balance '+balance);}
  function run(){var sims=Math.min(10000,Math.floor(val('mco-sims'))),trades=Math.min(1000,Math.floor(val('mco-trades'))),wr=val('mco-wr')/100,rr=val('mco-rr'),risk=val('mco-risk')/100,balance=val('mco-balance'),rate=val('mco-rate'),random=rng(val('mco-seed'));if(!(sims>0&&trades>0&&wr>=0&&wr<=1&&rr>0&&risk>0&&risk<1&&balance>0&&rate>0))return;var finals=[],dds=[],streaks=[],ruined=0;for(var s=0;s<sims;s++){var equity=1,peak=1,maxdd=0,streak=0,maxstreak=0,hit=false;for(var i=0;i<trades;i++){if(random()<wr){equity*=1+risk*rr;streak=0;}else{equity*=1-risk;streak++;maxstreak=Math.max(maxstreak,streak);}peak=Math.max(peak,equity);maxdd=Math.max(maxdd,(peak-equity)/peak);if(equity<=.5)hit=true;}finals.push(equity);dds.push(maxdd);streaks.push(maxstreak);if(hit)ruined++;}var metrics=[[T.median,F.money(percentile(finals,50)*balance)+' / '+Math.round(percentile(finals,50)*balance*rate).toLocaleString(F.numLocale)+' UZS'],[T.bad,F.money(percentile(finals,5)*balance)],[T.dd,pct(percentile(dds,50))],[T.dd95,pct(percentile(dds,95))],[T.loss,pct(finals.filter(function(v){return v<1;}).length/sims)],[T.dd20,pct(dds.filter(function(v){return v>=.2;}).length/sims)],[T.ruin,pct(ruined/sims)],[T.streak,Math.round(percentile(streaks,95))]];var result=document.getElementById('mco-result');result.innerHTML='<div class="fx-metrics">'+metrics.map(function(m){return'<div><span>'+m[0]+'</span><strong>'+m[1]+'</strong></div>';}).join('')+'</div>';result.hidden=false;draw(finals,balance);if(window.fxTrack)window.fxTrack('monte_carlo_completed',{once:false});}
  document.getElementById('mco-run').addEventListener('click',run);
})();
